version: '3.8'
services:
  webapp:
    container_name: webapp  
    image: webapp
    build:
      context: . 
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database

# Run: docker compose up -d