version: '3.8'
services:

  webapp:
    container_name: webapp  
    image: hannelorem/webapp:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://database:27017
    depends_on:
      - database
  
  test:
    container_name: test
    image: hannelorem/webapp:latest
    command: yarn test
    environment:
      - API_URL=http://webapp:3000
    depends_on:
      - webapp

  database:
    container_name: mongo
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      
volumes:
  mongodb_data:

# Run: docker compose up -d
# docker compose up -d test