name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        run: |
          yarn install
          yarn lint
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push and build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hannelorem/webapp:latest
